### PR TITLE
Resolving `ExecuteAudit` function getting Breaked Easily 

### PR DESCRIPTION
**Pull request by Jay-sanjay**
fixing #48

### CODE REVIEW

**Comment by TheCedarPrince** [comment]
Hey @Jay-sanjay ! Thanks for working on this! The functionality looks perfect -- could you just add in one test testing the auditing of a DataFrame by passing a value to the kwarg? Once you add the test, this should be set for merging! :smile: Great work!

**Review by TheCedarPrince — CHANGES_REQUESTED** [review]
See comment above about the test we need.

**Review by TheCedarPrince — APPROVED** [review]
LGTM -- let's merge it! Great work and thanks @Jay-sanjay ! :smile:

**Comment by Jay-sanjay** [comment]
Thanks !! again

**Pull request merged**
