### PR TITLE
Added GetDrugExposureStartDate function

### PR DESCRIPTION
**Pull request by Jay-sanjay**
This PR is related to #68 

## PR CheckList

- [x] Added the function and it's 3 dispatches.
- [x] Added the required test cases for the function.
- [x] Updated the docs with the new function

### CODE REVIEW

**Review by TheCedarPrince — APPROVED** [review]
LGTM -- slap it into the repo! :wave:

**Comment by TheCedarPrince** [comment]
Hey @Jay-sanjay , could you remind me, what is keeping this PR from being merged? Do you need me to do something?

**Comment by Jay-sanjay** [comment]
@TheCedarPrince  One thing before I merge that PR,  I see if here we want to add regarding writing sql returning  in the doc-string here https://github.com/JuliaHealth/OMOPCDMCohortCreator.jl/blob/15b850008dc92c091e58695f34791d58dd607a84/src/getters.jl#L1956 then I guess we need to update the the doc-string of almost all getters functions
like - https://github.com/JuliaHealth/OMOPCDMCohortCreator.jl/blob/ac5bcf02a67ff0afe7868c6d77b61674daa2795e/src/getters.jl#L1550Am I pointing correctly, or did I do a mistake

**Comment by TheCedarPrince** [comment]
I see what you mean. I am going to say, let's merge this now and create another separate documentation PR that fixes this across all functions. In theory, it should be a kinda fast grep and replace...

**Pull request merged**
